#!/bin/bash
path_files=""
sed 's/@/@user=/g' users > temp
sed 's/,/ or /g' temp > u
rm temp
for i in $(seq $1 $2)
do	
	#curl -O http://planet.openstreetmap.org/replication/day/000/000/$1.osc.gz
	gzip -d $i.osc.gz	
   	./osmfilter $i.osc --keep="\"$(cat u)\"" -o=$i.osm
    node index.js --osmfile=$i.osm --boundfile=$3 --path=$path_files
    ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres dbname=dbtiger" -append us-$i.geojson
    echo $i.osc
    rm $i.osm
    rm us-$i.geojson
done
rm u
