#!/bin/bash
path_files=""
users=(Rub21 ediyes RichRico Luis36995 dannykath andygol shravan91 ruthmaben abel801 samely calfarome srividya_c PlaneMad)
for f in $(seq $1 $2)
do	
	#curl -O http://planet.openstreetmap.org/replication/day/000/000/$1.osc.gz
	#gzip -d $1.osc.gz	
	for i in ${users[*]}
	do    	
    	./osmfilter $f.osc --keep="@user=$i" -o=$i.osm
    	echo node index.js --osmfile=$i.osm --boundfile=$3 --path=$path_files
	done
done

